name: Release

on:
  push:
    branches:
      - pratyush

jobs:
  build-and-publish-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry install
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry build
          twine upload --repository pypi dist/*